version: 0.2
phases:
  install: 
    commands: 
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip"
      - "unzip terraform_1.1.7_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - pwd
      - cd Profiles 
      - terraform init -backend-config="bucket=casestudy-backend-bucket" -backend-config="key=state/terraform.tfstate" -backend-config="region=us-east-1" -backend-config="encrypt=true" -backend-config="dynamodb_table=terraform-state-lock-dynamo"
      - terraform workspace select dev || terraform workspace new dev
  
  build:
    commands:
      - terraform plan -var-file="../environment/input_vars.tfvars"
      - terraform apply -var-file="../environment/input_vars.tfvars" -auto-approve 